FROM node:20-alpine AS builder

WORKDIR /app

COPY web/package.json ./
RUN npm install

COPY web/ ./
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3050

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3050

CMD ["node", "server.js"]
