package engine

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/google/uuid"
)

type LibreOfficeDocumentConverter struct {
	sofficePath string
}

func NewLibreOfficeDocumentConverter() *LibreOfficeDocumentConverter {
	// Discover soffice binary
	candidates := []string{
		"soffice",
		"libreoffice",
		"/usr/bin/soffice",
		"/usr/bin/libreoffice",
		`C:\Program Files\LibreOffice\program\soffice.exe`,
		`C:\Program Files (x86)\LibreOffice\program\soffice.exe`,
	}

	selected := "soffice"
	for _, c := range candidates {
		if path, err := exec.LookPath(c); err == nil {
			selected = path
			break
		}
		if _, err := os.Stat(c); err == nil {
			selected = c
			break
		}
	}

	return &LibreOfficeDocumentConverter{
		sofficePath: selected,
	}
}

func (l *LibreOfficeDocumentConverter) Name() string {
	return "libreoffice_headless"
}

// ConvertToPDF converts any supported document (DOCX, XLSX, PPTX, RTF, ODT, TXT, HTML) to PDF.
func (l *LibreOfficeDocumentConverter) ConvertToPDF(ctx context.Context, inputPath string, outputPath string) error {
	return l.runConversion(ctx, inputPath, "pdf", outputPath)
}

// ConvertDocument converts an input document to a target extension format (e.g. docx, odt, rtf, txt, html).
func (l *LibreOfficeDocumentConverter) ConvertDocument(ctx context.Context, inputPath string, targetExt string, outputPath string) error {
	return l.runConversion(ctx, inputPath, targetExt, outputPath)
}

// ExtractText extracts plain text from PDF or office documents.
func (l *LibreOfficeDocumentConverter) ExtractText(ctx context.Context, inputPath string, outputPath string) error {
	// If input is PDF, attempt pdftotext first (faster and lighter)
	if strings.HasSuffix(strings.ToLower(inputPath), ".pdf") {
		if pdftotext, err := exec.LookPath("pdftotext"); err == nil {
			cmd := exec.CommandContext(ctx, pdftotext, "-layout", inputPath, outputPath)
			var stderr bytes.Buffer
			cmd.Stderr = &stderr
			if err := cmd.Run(); err == nil && fileExists(outputPath) {
				return nil
			}
		}
	}

	// Fallback to LibreOffice txt conversion
	return l.runConversion(ctx, inputPath, "txt:Text", outputPath)
}

// ConvertToHTML converts document to HTML/XHTML format.
func (l *LibreOfficeDocumentConverter) ConvertToHTML(ctx context.Context, inputPath string, outputPath string) error {
	// If input is PDF, attempt pdftohtml first
	if strings.HasSuffix(strings.ToLower(inputPath), ".pdf") {
		if pdftohtml, err := exec.LookPath("pdftohtml"); err == nil {
			cmd := exec.CommandContext(ctx, pdftohtml, "-s", "-c", "-noframes", inputPath, outputPath)
			var stderr bytes.Buffer
			cmd.Stderr = &stderr
			if err := cmd.Run(); err == nil && fileExists(outputPath) {
				return nil
			}
		}
	}

	return l.runConversion(ctx, inputPath, "html:XHTML", outputPath)
}

var safeFilterRegex = regexp.MustCompile(`^[a-zA-Z0-9_\-:]+$`)

func (l *LibreOfficeDocumentConverter) runConversion(ctx context.Context, inputPath string, filterOrExt string, outputPath string) error {
	if !fileExists(inputPath) {
		return fmt.Errorf("input file not found: %s", inputPath)
	}

	filterOrExt = strings.TrimSpace(filterOrExt)
	if !safeFilterRegex.MatchString(filterOrExt) || len(filterOrExt) > 32 {
		return fmt.Errorf("invalid format or filter specified: %s", filterOrExt)
	}

	targetExt := filterOrExt
	if idx := strings.Index(filterOrExt, ":"); idx != -1 {
		targetExt = filterOrExt[:idx]
	}


	// Create ephemeral scratch directory and isolated user installation
	tempDir, err := os.MkdirTemp("", "lipdf_lo_")
	if err != nil {
		return fmt.Errorf("failed to create temp dir: %w", err)
	}
	defer os.RemoveAll(tempDir)

	profileDir := filepath.Join(tempDir, "profile_"+uuid.NewString())
	_ = os.MkdirAll(profileDir, 0700)

	// Format URL for -env:UserInstallation
	profileURI := fmt.Sprintf("file:///%s", filepath.ToSlash(filepath.Clean(profileDir)))
	profileURI = strings.Replace(profileURI, "file:////", "file:///", 1)

	outDir := filepath.Join(tempDir, "out")
	_ = os.MkdirAll(outDir, 0755)

	args := []string{
		"--headless",
		"--invisible",
		"--nodefault",
		"--nofirststartwizard",
		"--nolockcheck",
		"--nologo",
		"--norestore",
		fmt.Sprintf("-env:UserInstallation=%s", profileURI),
		"--convert-to", filterOrExt,
		"--outdir", outDir,
		inputPath,
	}

	cmd := exec.CommandContext(ctx, l.sofficePath, args...)
	var stderr bytes.Buffer
	var stdout bytes.Buffer
	cmd.Stderr = &stderr
	cmd.Stdout = &stdout

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("libreoffice conversion failed: %w (stderr: %s, stdout: %s)", err, stderr.String(), stdout.String())
	}

	// Identify generated file in outDir
	entries, err := os.ReadDir(outDir)
	if err != nil || len(entries) == 0 {
		return fmt.Errorf("no output generated by libreoffice (filter: %s, stderr: %s)", filterOrExt, stderr.String())
	}

	// Find the matching generated file
	var generatedFile string
	inputBase := strings.TrimSuffix(filepath.Base(inputPath), filepath.Ext(inputPath))

	for _, entry := range entries {
		if !entry.IsDir() {
			name := entry.Name()
			if strings.HasPrefix(name, inputBase) || strings.HasSuffix(strings.ToLower(name), "."+strings.ToLower(targetExt)) {
				generatedFile = filepath.Join(outDir, name)
				break
			}
		}
	}

	if generatedFile == "" && len(entries) > 0 {
		generatedFile = filepath.Join(outDir, entries[0].Name())
	}

	if !fileExists(generatedFile) {
		return fmt.Errorf("generated output file is missing or empty")
	}

	// Copy/move generated file to destination outputPath
	_ = os.MkdirAll(filepath.Dir(outputPath), 0755)
	if err := copyOrMove(generatedFile, outputPath); err != nil {
		return fmt.Errorf("failed to place output file: %w", err)
	}

	return nil
}

func copyOrMove(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Sync()
}
