from typing import Dict, List, Optional
from .models import DocumentSpec

SPECS_DATABASE: Dict[str, DocumentSpec] = {
    "in_passport": DocumentSpec(
        id="in_passport",
        country="India",
        country_code="IN",
        name="India Passport",
        category="passport",
        width_mm=35.0,
        height_mm=45.0,
        dpi=300,
        face_coverage_min_pct=0.70,
        face_coverage_max_pct=0.80,
        crown_to_top_margin_pct=0.08,
        eye_level_from_bottom_min_pct=0.52,
        eye_level_from_bottom_max_pct=0.68,
        default_background_color="#FFFFFF",
        allowed_background_colors=["#FFFFFF", "#F3F4F6", "#E5E7EB"],
        description="35 x 45 mm, 70-80% face ratio, plain white or light background.",
        notes="Face should occupy 31.5mm to 36mm of vertical space. Plain white background mandatory."
    ),
    "in_visa": DocumentSpec(
        id="in_visa",
        country="India",
        country_code="IN",
        name="India Visa / OCI",
        category="visa",
        width_mm=51.0,  # 2 x 2 inches
        height_mm=51.0,
        dpi=300,
        face_coverage_min_pct=0.55,
        face_coverage_max_pct=0.70,
        crown_to_top_margin_pct=0.10,
        eye_level_from_bottom_min_pct=0.50,
        eye_level_from_bottom_max_pct=0.65,
        default_background_color="#FFFFFF",
        allowed_background_colors=["#FFFFFF", "#F9FAFB"],
        description="51 x 51 mm (2x2 inch), square photo with white background.",
        notes="Standard 2x2 inch format for Indian Visa & OCI applications."
    ),
    "in_aadhaar": DocumentSpec(
        id="in_aadhaar",
        country="India",
        country_code="IN",
        name="India Aadhaar / ID",
        category="id",
        width_mm=35.0,
        height_mm=45.0,
        dpi=300,
        face_coverage_min_pct=0.65,
        face_coverage_max_pct=0.75,
        crown_to_top_margin_pct=0.08,
        eye_level_from_bottom_min_pct=0.50,
        eye_level_from_bottom_max_pct=0.68,
        default_background_color="#FFFFFF",
        allowed_background_colors=["#FFFFFF", "#F3F4F6", "#E5E7EB", "#E0F2FE"],
        description="35 x 45 mm, standard government identity card format.",
        notes="White or light off-white background."
    ),
    "in_pan": DocumentSpec(
        id="in_pan",
        country="India",
        country_code="IN",
        name="India PAN Card",
        category="id",
        width_mm=25.0,
        height_mm=35.0,
        dpi=300,
        face_coverage_min_pct=0.65,
        face_coverage_max_pct=0.75,
        crown_to_top_margin_pct=0.08,
        eye_level_from_bottom_min_pct=0.50,
        eye_level_from_bottom_max_pct=0.68,
        default_background_color="#FFFFFF",
        allowed_background_colors=["#FFFFFF", "#F3F4F6"],
        description="25 x 35 mm, compact portrait format for NSDL/UTIITSL PAN cards.",
        notes="Clear white background, both ears visible."
    ),
    "us_passport_visa": DocumentSpec(
        id="us_passport_visa",
        country="United States",
        country_code="US",
        name="US Passport / Visa",
        category="passport",
        width_mm=51.0,  # 2 x 2 inches (50.8mm round to 51mm)
        height_mm=51.0,
        dpi=300,
        face_coverage_min_pct=0.50,
        face_coverage_max_pct=0.69,
        crown_to_top_margin_pct=0.10,
        eye_level_from_bottom_min_pct=0.56,
        eye_level_from_bottom_max_pct=0.69,
        default_background_color="#FFFFFF",
        allowed_background_colors=["#FFFFFF", "#FAFAFA"],
        description="2 x 2 inch (51 x 51 mm), head between 1 and 1 3/8 inches (50-69%).",
        notes="Plain white or off-white background. Neutral facial expression, no glasses."
    ),
    "uk_passport": DocumentSpec(
        id="uk_passport",
        country="United Kingdom",
        country_code="GB",
        name="UK Passport",
        category="passport",
        width_mm=35.0,
        height_mm=45.0,
        dpi=300,
        face_coverage_min_pct=0.64,
        face_coverage_max_pct=0.75,
        crown_to_top_margin_pct=0.08,
        eye_level_from_bottom_min_pct=0.52,
        eye_level_from_bottom_max_pct=0.68,
        default_background_color="#E5E7EB",  # Light grey
        allowed_background_colors=["#E5E7EB", "#F3F4F6", "#D1D5DB", "#FFFFFF"],
        description="35 x 45 mm, head 29-34 mm, plain light grey or cream background.",
        notes="Light grey background recommended for HM Passport Office."
    ),
    "schengen_visa": DocumentSpec(
        id="schengen_visa",
        country="Schengen Area",
        country_code="EU",
        name="Schengen Visa",
        category="visa",
        width_mm=35.0,
        height_mm=45.0,
        dpi=300,
        face_coverage_min_pct=0.70,
        face_coverage_max_pct=0.80,
        crown_to_top_margin_pct=0.08,
        eye_level_from_bottom_min_pct=0.52,
        eye_level_from_bottom_max_pct=0.68,
        default_background_color="#E5E7EB",
        allowed_background_colors=["#E5E7EB", "#F3F4F6", "#FFFFFF"],
        description="35 x 45 mm, 70-80% face height (32-36 mm), light background.",
        notes="Light grey or light neutral background without patterns or shadows."
    ),
    "ca_passport": DocumentSpec(
        id="ca_passport",
        country="Canada",
        country_code="CA",
        name="Canada Passport",
        category="passport",
        width_mm=50.0,
        height_mm=70.0,
        dpi=300,
        face_coverage_min_pct=0.44,  # 31-36 mm on 70mm height
        face_coverage_max_pct=0.52,
        crown_to_top_margin_pct=0.12,
        eye_level_from_bottom_min_pct=0.50,
        eye_level_from_bottom_max_pct=0.65,
        default_background_color="#FFFFFF",
        allowed_background_colors=["#FFFFFF", "#F9FAFB"],
        description="50 x 70 mm, head height 31-36 mm, plain white or light background.",
        notes="Unique 50x70mm aspect ratio required by Passport Canada."
    ),
    "au_passport": DocumentSpec(
        id="au_passport",
        country="Australia",
        country_code="AU",
        name="Australia Passport",
        category="passport",
        width_mm=35.0,
        height_mm=45.0,
        dpi=300,
        face_coverage_min_pct=0.71,  # 32-36 mm
        face_coverage_max_pct=0.80,
        crown_to_top_margin_pct=0.08,
        eye_level_from_bottom_min_pct=0.52,
        eye_level_from_bottom_max_pct=0.68,
        default_background_color="#E5E7EB",
        allowed_background_colors=["#E5E7EB", "#F3F4F6", "#FFFFFF"],
        description="35 x 45 mm, head 32-36 mm, plain white or light grey background.",
        notes="Australian Passport Office guidelines."
    ),
    "sg_passport": DocumentSpec(
        id="sg_passport",
        country="Singapore",
        country_code="SG",
        name="Singapore Passport",
        category="passport",
        width_mm=35.0,
        height_mm=45.0,
        dpi=300,
        face_coverage_min_pct=0.70,
        face_coverage_max_pct=0.80,
        crown_to_top_margin_pct=0.08,
        eye_level_from_bottom_min_pct=0.52,
        eye_level_from_bottom_max_pct=0.68,
        default_background_color="#FFFFFF",
        allowed_background_colors=["#FFFFFF", "#F9FAFB"],
        description="35 x 45 mm, white background, ICA Singapore compliance.",
        notes="Direct frontal view, even lighting, plain white background."
    ),
    "custom_35x45": DocumentSpec(
        id="custom_35x45",
        country="Custom",
        country_code="XX",
        name="Standard ID (35 x 45 mm)",
        category="custom",
        width_mm=35.0,
        height_mm=45.0,
        dpi=300,
        face_coverage_min_pct=0.65,
        face_coverage_max_pct=0.80,
        crown_to_top_margin_pct=0.08,
        default_background_color="#FFFFFF",
        allowed_background_colors=["#FFFFFF", "#F3F4F6", "#E5E7EB", "#3B82F6", "#EF4444"],
        description="Standard 35 x 45 mm for general corporate / school / member badges.",
        notes="Custom background colors permitted."
    )
}

def get_spec(spec_id: str) -> Optional[DocumentSpec]:
    return SPECS_DATABASE.get(spec_id)

def list_all_specs() -> List[DocumentSpec]:
    return list(SPECS_DATABASE.values())
